server:
  port: 8090
  servlet:
    context-path: /
spring:
  redis:
    host:192.168.100.25
    port:6379
    password:123456
  application:
    name: space
  datasource:
    druid:
      url: jdbc:mysql://192.168.100.20/Orderingsystem?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html

mybatis:
  type-aliases-package: com.yhy.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



